### ISSUE TITLE
Broken on new patch

### ISSUE THREAD

**Issue by ChangoTheBeast** [ricardosouzag/ModInstaller#102]
Needs updating to work with the latest patch that was released on the 7th June. Currently, the mod installer will not open on this patch.

**Comment by mandar1jn** [comment]
@rlouch this is a known issue. Sadly this can't be fixed until the new version of the modding API is released

**Comment by tommaier123** [comment]
How does the mod installer detect the game version/which version does it want. I tried downgrading on Steam but the installer didn't take the version from March.

**Comment by mandar1jn** [comment]
Then you did something wrong downgrading hollow knight

**Comment by fifty-six** [comment]
New patch has a new installer
