### ISSUE TITLE
Mod installer breaks down if a mod lists a dependency that can not be automatically installed

### ISSUE THREAD

**Issue by Naharie** [ricardosouzag/ModInstaller#88]
More or less as the title says. This results in a rather user unfriendly error message.
"Sequence contains no matching element."

![Error](https://user-images.githubusercontent.com/12404374/115171063-6c1c0b00-a07f-11eb-94d2-59e20e9e5358.png)

**Comment by JupiterSky11** [comment]
My friend is also having this issue, would like to know if there's a fix.

**Comment by Naharie** [comment]
@JupiterSky11 I've opened a pull request with a fix on the mod installer side. For now though if you know the Hollow Knight install path, go there and then into hollow_knight_Data/Managed and delete the Mods folder. Yes, that does mean you will have to reinstall all your mods. Just make sure to go slowly and check after each one or two whether or not it is the one causing the crash.

**Comment by JupiterSky11** [comment]
@Naharie we ended up doing that very thing, thanks for the help though!

**Comment by Ruttie2006** [comment]
I have posted it on the HK server, hopefully it will get merged soon. :)

**Comment by mandar1jn** [comment]
#89 should fix this issue

**Comment by Ruttie2006** [comment]
@mandar1jn 
the pr was made by the same person

**Comment by mandar1jn** [comment]
Oh.
