### ISSUE TITLE
Path is denied

### ISSUE THREAD

**Issue by ClaudiuXVXVX** [ricardosouzag/ModInstaller#91]
I selected the path to the game but it says "Access to the path is denied".
![image](https://user-images.githubusercontent.com/83120742/115957433-1629e600-a50b-11eb-87ec-24be9309e3c5.png)

**Comment by Ruttie2006** [comment]
@ClaudiuXVXVX 
1. this does not seem like a official installation.
2. only Steam and GoG releases can be modded.

**Comment by Ruttie2006** [comment]
https://discord.gg/hollowknight
